//
//  TabbarWireframe.swift
//  Template
//
//  Created by Levente Vig on 2020. 12. 11..
//  Copyright (c) 2020. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class TabbarWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init(selctedTab: Int = 0) {
        let moduleViewController = TabbarViewController()
        super.init(viewController: moduleViewController)
        
        let interactor = TabbarInteractor()
        let presenter = TabbarPresenter(view: moduleViewController, interactor: interactor, wireframe: self, selectedTab: selctedTab)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension TabbarWireframe: TabbarWireframeInterface {
}
