# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  #############################################################
  # => Generate project structure and install dependencies <= #
  #############################################################
  desc 'Update and install dependencies'
  lane :generate_project do |options|
    sh("cd ../Template/Resources/Generated && rm -rf Generated && mkdir Generated")
    sh("cd .. && swiftgen -v")
    sh("cd .. && xcodegen generate")
  end
end
